# Generated by Django 4.1.7 on 2023-03-31 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_image'),
        ('carts', '0003_cartproduct'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartProduct',
            new_name='CartProducts',
        ),
    ]
